global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter-service:9308']
  - job_name: 'classroom-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'classroom-service:8090' ]